name: 'PR-LABELER'
description: 'Automatically label new pull requests based on the paths of files being changed'
author: 'GitHub'
inputs:
  repo-token:
    description: 'The GitHub token used to manage labels'
    required: false
    default: ${{ github.token }}
  yml-path:
    description: 'The path for the label configurations'
    default: '.github/labeler.yml'
    required: false
  sync-labels:
    description: 'Whether or not to remove labels when matching files are reverted'
    default: true
    required: false
outputs:
  new-labels:
    description: 'A comma-separated list of all new labels'
  all-labels:
    description: 'A comma-separated list of all labels that the PR contains'
runs:
  using: 'node16'
  main: 'dist/index.js'