on:
  workflow_call:
    inputs:
      yml-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Labeler
        uses: ./.github/actions/semantic_labeler
        with:
          repo-token: ${{ secrets.token }}
          yml-path: ${{ inputs.yml-path }}